name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Dependencies
      run: bin/carthage.sh bootstrap --cache-builds --platform ios
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app
    - name: Run Tests
      run: xcodebuild -project Turbo -scheme Turbo test -quiet -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      env:
        DEVELOPER_DIR: //Applications/Xcode_12.2.app
