name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Cache carthage
      uses: actions/cache@v2
      with:
        path: Carthage
        key: carthage-xcode12.2-${{ hashFiles('Cartfile.resolved') }}
        restore-keys: |
          carthage-xcode12.2
          carthage-

    - name: Build Dependencies
      run: bin/carthage.sh bootstrap --cache-builds --platform ios
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app

    - name: Run Tests
      run: xcodebuild -project Turbo.xcodeproj -scheme Turbo test -quiet -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app
